#!/usr/bin/env bash

mc_port=25565
port=${1:-${PORT:-8080}}

if [ -z "$NGROK_API_TOKEN" ]; then
  echo "You must set the NGROK_API_TOKEN config var to create a TCP tunnel!"
  exit 1
fi

if [ -z "$MINECRAFT_RAM" ]; then
  MINECRAFT_RAM=256
fi

# Start the TCP tunnel
ngrok_cmd="bin/ngrok tcp -authtoken $NGROK_API_TOKEN -log stdout --log-level debug ${NGROK_OPTS} ${mc_port}"
echo "Starting ngrok..."
eval "$ngrok_cmd | tee ngrok.log &"
ngrok_pid=$!

# create server config
echo "server-port=${mc_port}" >> /app/server.properties
touch whitelist.json
touch banned-players.json
touch banned-ips.json
touch ops.json

heap="$(MINECRAFT_RAM)m"

echo "Starting: minecraft ${mc_port}"
eval "java -Xmx${heap} -Xms${heap} -jar forge-1.7.10-10.13.4.1492-1.7.10-universal.jar nogui &"
main_pid=$!
echo "minecraft started on port: ${port}"

trap "kill $ngrok_pid $main_pid" SIGTERM
trap "kill -9 $ngrok_pid $main_pid; exit" SIGKILL

eval "ruby -rwebrick -e'WEBrick::HTTPServer.new(:BindAddress => \"0.0.0.0\", :Port => ${port}, :MimeTypes => {\"rhtml\" => \"text/html\"}, :DocumentRoot => Dir.pwd).start'"
